# Generated by Django 2.1 on 2018-10-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elementintown',
            name='elem',
        ),
        migrations.AddField(
            model_name='elementintown',
            name='elem',
            field=models.ManyToManyField(to='shop.Elements'),
        ),
        migrations.RemoveField(
            model_name='elementintown',
            name='store',
        ),
        migrations.AddField(
            model_name='elementintown',
            name='store',
            field=models.ManyToManyField(to='shop.StoreTown'),
        ),
    ]
