# Generated by Django 2.1 on 2018-10-12 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20181012_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementintown',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.StoreTown'),
        ),
    ]
